services:
  # ─── PostgreSQL ───
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  # ─── Kafka ───
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # ─── Kafka UI ───
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092


  user-service:
    build: ../sr-user-service
    ports:
      - "50051:50051"
    environment:
      DB_HOST: postgres      
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_DATABASE: sr_users_db
    depends_on:
      - postgres
  
  question-service:
    build: ../sr-question-service
    ports:
      - "50052:50051"
    environment:
      DB_HOST: postgres      
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_DATABASE: sr_questions_db
    depends_on:
      - postgres

  study-service:
    build: ../sr-study-service
    ports:
      - "50053:50051"
    environment:
      DB_HOST: postgres      
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_DATABASE: sr_study_db
      QUESTION_SERVICE_ADDR: question-service:50051
    depends_on:
      - postgres
      - question-service

volumes:
  pgdata:
